version: "3"
services:
  punktube:
    image: punx:latest
    hostname: punktube
    container_name: punktube
    mac_address: 02:42:c0:a8:84:22
    networks:
      ytdl_vlan:
        ipv4_address: 10.121.122.60
    ports:
      - "80:80"
    environment:
      - UID=1020
      - GID=1001
    volumes:
      - /mnt/gstf-ng-video2/inbox/punktube-XTEST:/downloads
      - /var/docker/services/metube/cookies:/cookies
networks:
  plex_net:
    external: true
  nginx_vlan:
    driver: macvlan
    driver_opts:
      parent: ens3
    ipam:
      driver: default
      config:
        - subnet: 10.121.122.0/24
          gateway: 10.121.122.1
